jaguarete/jaguarete/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# Importo las urls de mi aplicación en el root del servicio.
urlpatterns = [
    path('', include('tienda.urls')),
    path('u/', include('usuarios.urls')),
    path('admin/', admin.site.urls)
]

if getattr(settings, 'DEBUG', False):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jaguarete/tienda/urls.py
from django.urls import path
from . import views

# En este archivo se definirán los linkeos a las views de la aplicación "Tienda".
app_name = "tienda"
urlpatterns = [
    path("", views.home, name="home"),
    path("nosotros/", views.about, name="about"),
    
    # Productos
    path("p/<int:prodId>", views.producto, name="producto"),

    # Para "nuevo" uso la misma view que editar, y decido internamente
    # como armar el form y los botones a presentar.
    path("p/editar/<int:prodId>", views.editarProducto, name="editar"),
    path("p/nuevo", views.editarProducto, name="nuevo"),
    path("p/eliminar", views.eliminarProducto, name="eliminar"),

    # Busqueda/Filtro
    path("busqueda/", views.busqueda, name="busqueda"),
    path("categoria/<str:cat>", views.busqueda, name="categorias"),
    
    # Usuario
    path("perfil/", views.perfil, name="perfil"),
    path("salir/", views.salir, name="salir"),
    
    # Carro
    path("agregar?P<int:prodId>&ref=<path:next>", views.agregarAlCarro, name="agregarAlCarro"),
    path("sacar?P<int:prodId>", views.sacarDelCarro, name="sacar"),
    path("vaciar", views.vaciarCarro, name="vaciar"),
    path("carro/", views.verCarro, name="carro"),
]

jaguarete/tienda/forms.py
from django import forms
from .models import Categoria, Producto

class FormProducto(forms.ModelForm):
    # Defino un nuevo campo "Nueva Categoria", por si la que corresponde no se
    # encuentra en la base de datos. Puede estar en blanco.
    nueva_cat = forms.CharField(max_length=32, label="Nueva Categoría")

    class Meta:
        model = Producto
        fields = '__all__'

    # Similar a con los usuarios, agrego placeholdes y clases por si
    # quiero estilizar luego.
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nombre'].label = "Nombre del Producto"
        self.fields['imagen'].label = "Imagen"
        self.fields['descr'].label = "Descripción del producto"
        self.fields['precio'].label = "Precio"
        self.fields['categoria'].label = "Categoría"
        
        # Puedo dejar en blanco el form si agrego una nueva categoria.
        # Esto se revisa de todas formas en el clean().
        self.fields['categoria'].required = False
        self.fields['nueva_cat'].required = False
        
        self.fields['nueva_cat'].widget.attrs["class"] = "jag-text-form form-control"
        self.fields['nueva_cat'].widget.attrs["placeholder"] = "Agregar nueva categoría"

        self.fields['nombre'].widget.attrs["class"] = "jag-text-form form-control"
        self.fields['nombre'].widget.attrs["placeholder"] = self.fields['nombre'].label

        self.fields['imagen'].widget.attrs["class"] = "jag-text-form form-control"
        self.fields['imagen'].widget.initial_text = "Actual"
        self.fields['imagen'].widget.input_text = "Cambiar"
        self.fields['imagen'].widget.attrs["placeholder"] = self.fields['imagen'].label
        
        self.fields['descr'].widget.attrs["class"] = "jag-text-form form-control"
        self.fields['descr'].widget.attrs["placeholder"] = self.fields['descr'].label
        self.fields['precio'].widget.attrs["class"] = "jag-text-form form-control"
        self.fields['precio'].widget.attrs["placeholder"] = self.fields['precio'].label
        self.fields['categoria'].widget.attrs["class"] = "jag-text-form form-control"
        self.fields['categoria'].widget.attrs["placeholder"] = self.fields['categoria'].label

    # Método para validar el campo de cateogoría con los nuevos chequeos.
    def clean(self):
        # Limpio los campos iniciales.
        cleaned_data = super(FormProducto, self).clean()
        
        categoria = cleaned_data.get('categoria')
        nueva_cat = cleaned_data.get('nueva_cat')

        print(f"Values = Im' in...{categoria} {nueva_cat}")

        # Me aseguro que pasen solo uno de los dos campos.
        if (not (categoria or nueva_cat)) or (categoria and nueva_cat):
            raise forms.ValidationError({'categoria':["Complete uno de los campos de categoría.",]})
        elif not categoria:
            # Se agrego una nueva categoria.
            cat, status = Categoria.objects.get_or_create(nombre=nueva_cat)
            cleaned_data['categoria'] = cat

jaguarete/tienda/views.py
from django.shortcuts import redirect, render, reverse
from django.http import HttpResponseRedirect
from django.contrib import messages

# Decoradores.
from django.contrib.auth.decorators import login_required

# Modelos.
from django.db.models import Q
from .models import Categoria, Producto, Carro
from .forms import FormProducto

# Para busqueda recursiva con todas las palabras buscadas, 
# podria usar reduce.
from functools import reduce
import operator

# Funciones privadas de manejo de ayuda.
# Funcion de ayuda para todos los views que requieran obtener info del
# carro.
def obtenerCarroActual(user):
    # Obtener o crear el carro pendiente del usuario.
    try:
        carro = Carro.objects.get(usuario=user, pendiente=True)
    except:
        carro = None

    # En cualquier caso, retorno el carro.
    return carro


# Funcion para determinar si un usuario es moderador.
def esModerador(user):
    return user.groups.filter(name="moderador").exists()


# //////////////////////////////// VISTAS /////////////////////////////////// #

# View de la pantalla inicial - Home.
# Paso por contexto una lista con los últimos 10
# elementos ordenados de más a menos reciente.
def home(request):
    # Para actualizar modificar el Agregar/ir al carro, necesito
    # obtener el carro. Si no hay carro, el None tambien me sirve.
    carro = obtenerCarroActual(request.user)

    return render(request, "tienda/index.html", {
        'productos': Producto.objects.all().order_by('-id')[:10],
        'carro' : carro
    })


# View del sitio "Sobre Nosotros".
# Renderiza el template about.html que es simplemente
# un sitio estatico con info de la empresa.
def about(request):
    return render(request, "tienda/about.html")


# View del sitio de visualizacion de Producto.
def producto(request, prodId):
    
    #Antes que nada, redirijo a moderadores a "Editar Producto".
    if esModerador(request.user):
        return redirect('tienda:editar', prodId)
    
    # Si es cliente, sigo por acá.
    # Obtengo el producto identificado por el ID.
    try:
        prod = Producto.objects.get(pk=prodId)
    except:
        return render(request, "tienda/404.html", {
            "mensaje" : "Producto no encontrado",
        })

    # Para actualizar modificar el Agregar/ir al carro, necesito
    # obtener el carro. Si no hay carro, el None tambien me sirve.
    carro = obtenerCarroActual(request.user)

    # Si obtuve el producto.
    return render(request, "tienda/producto.html", {
        "producto" : prod,
        "carro" : carro
    })


# View para agregar o editar productos.
# Solo accesible para moderadores.
@login_required
def editarProducto(request, prodId=None):
    #Antes que nada, redirijo a clientes al "Home".
    if not esModerador(request.user):
        return redirect('tienda:home')
    
    # Si vengo de un POST, vengo con datos.
    if request.method == "POST":

        # Obtengo los campos del form, hay que hacer un pasaje previo con
        # prodId, porque en el campo del form obviamente se llena como 
        # Texto, en lugar de como un ID entero.
        prodstring = request.POST["prodId"]

        try:
            prodId = int(prodstring)
            inst = Producto.objects.get(id=prodId)
            mensaje = "Producto Modificado"
        except:
            # No se pudo convertir, probablemente el campo id era "None" y 
            # vengo de la pagina de agregar producto. Si la excepcion la tiro
            # objetcts.get, guardo como producto nuevo de todas formas.
            prodId = None
            inst = None
            mensaje = "Producto Agregado"

        # Ahora si, obtengo los campos del POST, y asocio con un objeto existente
        # si proId no era None.
        form = FormProducto(request.POST, request.FILES, instance=inst)

        # Verifico que la info sea valida, en cuyo caso, guardo el objeto
        # nuevo o modifico la instancia existente.
        if form.is_valid():
            form.save()
            messages.info(request, mensaje)

            # Redirijo al home.
            return redirect('tienda:home')

    # Si vengo de un GET, genero un form nuevo.
    else:
        if prodId is None:
            # Vengo de una solicitud de Nuevo producto, armo un
            # Form vacío.
            form = FormProducto()

        else:
            # Pasaron un ID, quiero editar un producto.
            # Obtengo el producto indicado.
            try:
                prod = Producto.objects.get(id=prodId)
            except:
                # Estan inventando o forzando urls, redirijo al home
                return redirect('tienda:home')

            # Id Valido, genero el form con los datos actuales del producto.
            form = FormProducto(instance=prod)

    return render(request, "tienda/editar_producto.html", {
        "form" : form,
        "prodId" : prodId,
    })


# View para eliminar Producto.
# Solo accesible para moderadores.
def eliminarProducto(request):
    # Antes que nada, verifico que el usuario sea moderador, y 
    # el método del request sea POST, para asegurarme que se 
    # llega por el boton de "Eliminar" producto en la página de 
    # edicion.
    if esModerador(request.user) and request.method == "POST":
        # Obtengo el ID del producto, que deberia llegar en un campo
        # oculto del request.
        prodId = request.POST["prodId"]
        
        # Si el campo es valido y el producto existe, lo elimino.
        if prodId and Producto.objects.filter(id=prodId).exists():
            Producto.objects.get(id=prodId).delete()
            messages.info(request, "Producto Eliminado")

    # En cualquier caso, finalmente redirijo al home.
    return redirect('tienda:home')


# View de la búsqueda de productos.
def busqueda(request, **kwargs):    
    # Chequeo que llegué aca desde la barra de busqueda con un POST.
    if request.method == 'POST':
        # Obtengo la frase buscada del request, y la convierto en una lista de 
        # palabras.
        palabras = request.POST['search-text'].split()

        # Chequeo por las dudas que no esté vacía.
        if not palabras:
            return HttpResponseRedirect(reverse("tienda:home"))

        # Hago una busqueda recursiva, donde tanto la descripcion o el nombre
        # tienen que contener todas las palabras buscadas.

        resultados = Producto.objects.filter(reduce(operator.and_, ((Q(nombre__contains=p) | Q(descr__contains=p)) for p in palabras)))

        # Retorno la pantalla de busqueda.
        return render(request, "tienda/search.html", {
            'frase' : ' '.join(palabras),
            'resultados' : resultados
        })

    else:
        # Request de GET, o sea que llego de los links de Categoria.
        
        # Obtengo el indice de la categoría. Si no se obtiene,  
        # no viene del link y redirijo al home.
        try:
            cat_id = Categoria.objects.get(nombre=kwargs['cat'])
        except:
            return HttpResponseRedirect(reverse("tienda:home"))

        # El proceso es similar, genero la lista de resultados a partir
        # de la categoria indicada en el link.
        resultados = Producto.objects.filter(categoria=cat_id)

        return render(request, "tienda/search.html", {
                          'categoria' : cat_id.nombre,
                          'resultados': resultados
                      })


# Vista de perfil de usuario.
# Esta vista podria presentar las preferencias del usuario, 
# lista de ordenes realizadas, y demás. Por lo pronto está fuera
# de los requerimientos, pero me sirve para darle un uso al "link"
# del nombre de usuario, y probar como funcionan los decoradores.
@login_required(login_url='usuarios:ingreso')
def perfil(request):
    return render(request, 'tienda/perfil.html')


# Agregar al carro.
# Esta view requiere un usuario logueado, al que asignar el carro, 
# Y no esta disponible para moderadores.
@login_required(login_url='usuarios:ingreso')
def agregarAlCarro(request, prodId, next):
    
    # Solo accesible para clientes, si algun moderador tipeó la direccion, 
    # lo redirecciono al home.
    if esModerador(request.user):
        return redirect('tienda:home')

    # Lo primero que hago es obtener o crear el carro pendiente 
    # del usuario.
    carroActual, status = Carro.objects.get_or_create(usuario=request.user, pendiente=True)

    # Obtengo el producto.
    p = Producto.objects.get(pk=prodId)

    # Agrego el producto al carro, y actualizo el total.
    carroActual.productos.add(p)
    carroActual.total = carroActual.listaTotal()
    carroActual.save()

    # Redirijo a la página de la que aprete el botón.
    messages.info(request, "Agregado al carro!")
    return HttpResponseRedirect(next)


# Funcion para sacar un producto del carro.
@login_required(login_url='tienda:home')
def sacarDelCarro(request, prodId):
    # Solo accesible para clientes, si algun moderador tipeó la direccion,
    # lo redirecciono al home.
    if esModerador(request.user):
        return redirect('tienda:home')
    
    # Si es cliente, continuo.
    carroActual = obtenerCarroActual(request.user)

    # Obtengo el producto.
    p = Producto.objects.get(pk=prodId)

    # Agrego el producto al carro, y actualizo el total.
    carroActual.productos.remove(p)
    carroActual.total = carroActual.listaTotal()
    carroActual.save()

    # Redirijo a la página de la que aprete el botón.
    return redirect('tienda:carro')


# Funcion para vaciar todo el carro.
@login_required(login_url='tienda:home')
def vaciarCarro(request):
    # Solo accesible para clientes, si algun moderador tipeó la direccion,
    # lo redirecciono al home.
    if esModerador(request.user):
        return redirect('tienda:home')

    # Obtengo el carro pendiente del usuario.
    carroActual = obtenerCarroActual(request.user)

    # Limpio todo el carro.
    carroActual.productos.clear()
    carroActual.total = carroActual.listaTotal()
    carroActual.save()

jaguarete/tienda/templates/tienda/about.html
{% extends "tienda/layout_general.html" %}
{% block private-body %}
{% load static %}
    <div class="container">
    
        <h1 class="py-4 text-center nova-dark">Jaguareté KAA</h1>
    
        {% comment %}
        Acá agrego la info de la empresa. Para hacer algo de diseño variable, 
        voy a hacer que en dispositivos grandes se muestre una imagen en un lateral, 
        mientras que en dispositivos chicos solo muestre la info.
        {% endcomment %}

        <div class="row g-5">
            <div class="col-lg-6 text-center text-lg-end">
                <h4 class="pb-2">¿Quienes somos?</h2>
                <p class ="pb-4">
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet esse autem harum beatae architecto illo porro natus
                    eius excepturi dignissimos quam modi ipsa impedit voluptas, aliquid temporibus consequuntur cumque dolores distinctio
                    neque maxime itaque, alias sit maiores. Quibusdam error natus dicta debitis delectus ducimus maxime vitae eos, quam a
                    sequi.
                </p>
            
            
                <h4 class="pb-2">Nuestros Productos</h2>
                <p class ="pb-2">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem quis nulla quam sint facere fugiat dignissimos ratione sit enim, tenetur optio culpa cupiditate, odit, consequatur quos amet quidem deserunt quaerat nobis officia. Rerum quo perspiciatis eius numquam magnam placeat voluptate harum voluptatibus, pariatur officiis consequuntur, assumenda totam veniam! Quaerat, corporis.
                </p>
            </div>

            <div id="aboutimg" class="col-lg-6 d-none d-lg-flex justify-content-center align-items-center">
                <img src="{% static 'images/jag-kaa-about.png' %}" class="img-fluid" style="width: 80%;">
            </div>
        </div>
    </div>

{% endblock %}

jaguarete/tienda/templates/tienda/carro.html
{% extends "tienda/layout_general.html" %}
{% block private-body %}

<div id="CarroMain" class="container">
    <h1 class="py-3 nova-dark">Tu Carro</h1>

    {% comment %}
    Acá estaría la pantalla de carro, en principio pienso en dos mitades en pantallas
    grandes y todo vertical en pantallas pequeñas. El primer div tendría el listado de 
    productos, y sus manejos, mientras que el segundo div tendrá los controles 
    para finalizar la compra.
    {% endcomment %}
    
    <div class="row g-3">
        <div id="CarroProductos" class="col-md-7">
            <h4 class="nova-dark">Productos en el Carro</h4>
            
            {% for prod in carro.listaProductos %}
            <div class="CarroItem my-2 d-flex"> 
                <div class=""> 
                    <a class="carro-prod d-block" href="{% url 'tienda:producto' prod.id %}">{{prod.nombre}}</a>
                    <span class="carro-precio" >{{prod.precioLocal}}</span> 
                </div>
                <a class="btn btn-sm btn-danger mb-auto ms-auto me-md-3" href="{% url 'tienda:sacar' prod.id %}">Eliminar</a>
            </div>
            {% empty %}
            <div class="my-4"> No hay productos en el carro</div>
            {% endfor %}

            {% if carro.listaProductos %}
            <a href="{% url 'tienda:vaciar' %}" class="btn boton-dark mt-3">Vaciar carro</a>
            {% endif %}
        </div>
        
        {% if carro.listaProductos %}
        <div id="CarroControles" class="col-md-5 text-center mb-3">

            <span class="d-block mt-4 mb-2">¿Tenés un cupón?</span>
            
            <input class="form-control jag-txt-form mx-auto" type="text" maxlength="8" name="cupon" id="cupon">
                        
            <hr class="mx-auto" style="width: 66%;">

            <h5 class="">Total del carro</h5>
            <h5 class="mb-4">{{ carro.totalLocal }}</h5>
            
            <input type="button" class="btn boton-accent mb-4" value="Finalizar Compra">
            {% endif %}
        </div>
    </div> <!-- end of row -->
</div>
{% endblock %}

jaguarete/tienda/templates/tienda/editar_producto.html
{% extends 'tienda/layout_general.html' %}
{% block private-body %}

{% comment %}
Esta pantalla sería muy similar a la de "Producto", pero todos los
campos donde antes tenia información ahora llevan forms para modificar
los valores. Tambien puede servir de pantalla de agregar nuevo producto, 
dependiendo de si se pasa o no un producto por contexto.
{% endcomment %}

{# Modal para confirmar eliminar producto. #}
<!-- Modal para eliminar productos -->
<div class="modal fade" id="eliminarModal" tabindex="-1" aria-labelledby="eliminarModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-danger text-light">
                <h5 class="modal-title" id="exampleModalLabel">Eliminar Producto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ¿Está seguro que desea eliminar el producto?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn boton-dark" data-bs-dismiss="modal">Volver</button>
                
                {% comment %}
                Implemento la eliminación de productos con un form con campos ocultos, 
                para asegurarme que solo se pueda llegar a dicha accion mediante un 
                request POST.                
                {% endcomment %}
                <form action="{% url 'tienda:eliminar' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="prodId" value="{{prodId}}">
                    <input type="submit" class="btn btn-danger" value="Eliminar">
                </form>
            </div>
        </div>
    </div>
</div>


<form enctype="multipart/form-data" action="{% url 'tienda:nuevo' %}" method="post">
    {% csrf_token %}
    <div id="ProductoMain" class="row">
        <div class="text-center my-4">
            {{ form.nombre }}
            <div class="my-2 text-danger text-start fw-bold">
                {{ form.nombre.errors }}
            </div>
        </div>
        
        <div class="col-12 col-sm-5 mb-5">
            <h5 class="my-3">Imagen de Producto:</h5>
            {{ form.imagen }}
            <div class="my-2 text-danger text-start fw-bold">
                {{ form.imagen.errors }}
            </div>    
        
        </div>
        <div id="ProductColumn" class="col-12 col-sm-7 d-flex flex-column mb-5">
            <hr class="dropdown-divider mt-0">
            {{ form.categoria }}
            {{ form.nueva_cat }}

            <div class="my-2 text-danger text-start fw-bold">
                {{ form.categoria.errors }}
            </div>
            
            <hr class="dropdown-divider">
            
            <div class="flex-fill">
                {{ form.descr }}
                <div class="my-2 text-danger text-start fw-bold">
                    {{ form.descr.errors }}
                </div>
            </div>
            <hr class="dropdown-divider mb-2">

            <div class="mx-auto my-2">
                {{ form.precio }}
                <div class="my-2 text-danger text-start fw-bold">
                    {{ form.precio.errors }}
                </div>
            </div>

            <div id="editControls" class="container d-flex justify-content-around mt-2">
                <input type="hidden" name="prodId" value="{{prodId}}">

                {# Si prodId es None, estoy en la página de "Agregar producto" #}
                {% if not prodId %}
                <input type="submit" value="Agregar Producto" class="btn boton-accent flex-fill mx-3">
                <a href="{% url 'tienda:home' %}" class="btn boton-dark">Volver</a>
                
                {% else %}
                <input type="submit" value="Guardar" class="btn boton-accent flex-fill mx-3">
                
                <!-- Boton para elimnar, dispara un modal. -->
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#eliminarModal">
                    Eliminar
                </button>
                {% endif %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

jaguarete/tienda/templates/tienda/index.html
{% extends "tienda/layout_general.html" %}

{% block private-body %}

{% comment %}
Acá deberían mostrarse los últimos 10 productos, donde los primeros 3 se presenten
en un formato estilo "card", con titulo, imagen y boton al producto. Los restantes 7
pueden presentarse en una lista de links.
{% endcomment %}

{% if not productos %}

<h1 class="nova-dark">No hay productos</h1>
<h3 class="nova-dark">Vuelva prontos...</h3>

{% else %}

<h1 class="pt-5 pb-3 nova-dark">ÚLTIMOS PRODUCTOS</h1>

<div class="container">
    
    {% comment %}
    En este div #productCards contiene los ultimos 3 elementos como 
    cards de Bootstrap.    
    {% endcomment %}

    <div id="productCards" class="row g-3">
        {% for prod in productos|slice:"0:3" %}
            <div class="col-6 col-md-5 col-lg-4 mb-2 mx-auto" style="min-width: 250px;"> 
                <div class="card h-100" >
                    <img src="{{ prod.imagen.url }}" class="card-img-top " alt="">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">{{prod.nombre}}</h5>
                        <div class="cardControls mt-auto">
                            <p class="card-text d-flex">{{prod.precioLocal}}</p>
                            <a href="{% url 'tienda:producto' prod.id %}" class="btn boton-accent">Ver</a>
                            

                            {# Este boton no tiene sentido si el usuario es moderador. #}
                            {% if not moderador %}
                                {% if prod in carro.listaProductos %}
                                    <a href="{% url 'tienda:carro' %}" class="btn boton-accent">Ir al Carro</a>
                                {% else %}
                                    <a href="{% url 'tienda:agregarAlCarro' prodId=prod.id next=request.path|urlencode %}" class="btn boton-accent">Agregar al Carro</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                    <h6 class="card-footer">{{prod.categoria}}</h6>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<h1 class="pt-5 pb-3 nova-dark">MÁS PRODUCTOS</h1>

<div class="container">

    {% comment %}
    Este otro div #productList va a contener los 7 productos restantes
    de la lista como links. Uso la stretched-link de bootstrap para
    que todo el div del elemento se considere como el link.
    {% endcomment %}
    
    <div id="productList" class="col-12">
        {% for prod in productos|slice:"3:10" %}
        <div class="productListItem position-relative">
            <h5>{{ prod.nombre.upper}}<span class="d-none d-sm-inline"> - {{prod.precioLocal}}</span></h1>
                <p class="d-block d-sm-none">{{ prod.precioLocal }}</p>
                <p class="d-none d-sm-block">{{ prod.descripcionCorta }}</p>
                <a href="{% url 'tienda:producto' prod.id %}" class="stretched-link"></a>
            <hr class="dropdown-divider">
        </div>
        {% endfor %}
    </div>

</div>

{% endif %}

{% endblock %}

jaguarete/tienda/templates/tienda/perfil.html
{% extends 'tienda/layout_general.html' %}

{% comment %}
Vista del Perfil de usuario.
{% endcomment %}

{% block private-body %}
<div class="container d-flex flex-column align-items-center">
    
    <h1 class="mt-3">
        Hola {{ user.first_name }}!
    </h1>

    <div class="mt-5">
        Acá irían la lista de ordenes, manejo de preferencias y ese tipo de cosas. 
    </div>
</div>

{% endblock %}

jaguarete/tienda/templates/tienda/producto.html
{% extends 'tienda/layout_general.html' %}

{% block private-body %}

{% comment %}
Template de producto, la estructura general esta en el documento de referencia.
Pero basicamente a partir de tamaño de pantallla sm parto la pantalla en 2, 
una zona mas pequeña para la imagen y por el otro lado una zona mayor con
la descripcion y controles del producto.
{% endcomment %}

<div id="ProductoMain" class="row">
    <h2 class="nova-dark text-center my-4"> {{ producto.nombre|upper }} </h2>
    <div class="col-12 col-sm-5 mb-5 text-center">
        <img src="{{ producto.imagen.url }}" class="img-fluid" alt="" style="width: 100%;max-width: 400px;">
    </div>
    <div id="ProductColumn" class="col-12 col-sm-7 d-flex flex-column mb-5">
        <hr class="dropdown-divider mt-0">
        <h6>{{ producto.categoria|upper }}</h6>
        <hr class="dropdown-divider mt-0">
        <div class="flex-fill">
            {{ producto.descr|linebreaks }}
        </div>
        <hr class="dropdown-divider mb-2">

        <span class="mx-auto my-2 fs-3 fw-normal">{{producto.precioLocal}}</span>

        {% if producto in carro.listaProductos %}
        <a href="{% url 'tienda:carro' %}" class="btn boton-accent">Ir al Carro</a>
        {% else %}
        <a href="{% url 'tienda:agregarAlCarro' prodId=producto.id next=request.path|urlencode %}" class="btn boton-accent">Agregar al Carro</a>
        {% endif %}
    </div>
</div>

{% endblock %}

jaguarete/tienda/templates/tienda/search.html
{% extends 'tienda/layout_general.html' %}

{% comment %}
Sitio para redireccionar en caso de errores de base de datos o lo que sea.
{% endcomment %}

{% block private-body %}
<div id="SearchMain" class="container d-flex flex-column align-items-center">
    <h1 class="nova-dark mt-3 mb-4 mb-sm-5">

    {% if frase %}
        Resultados de "{{frase}}"
    {% endif %}

    {% if categoria %}
        {{categoria}}
    {% endif %}
    </h1>

    <div id="productList" class="col-12">
        {% for prod in resultados %}
        <div class="productListItem position-relative">
            <h5>{{ prod.nombre.upper}}<span class="d-none d-sm-inline"> - {{prod.precioLocal}}</span></h1>
                <p class="d-block d-sm-none">{{ prod.precioLocal }}</p>
                <p class="d-none d-sm-block">{{ prod.descripcionCorta }}</p>
                <a href="{% url 'tienda:producto' prod.id %}" class="stretched-link"></a>
                <hr class="dropdown-divider">
        </div>
        {% empty %}
            <h3>No hay resultados para esta búsqueda</h3>
        {% endfor %}
    </div>

</div>
{% endblock %}