jaguarete/jaguarete/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# Importo las urls de mi aplicación en el root del servicio.
urlpatterns = [
    path('', include('tienda.urls')),
    path('u/', include('usuarios.urls')),
    path('admin/', admin.site.urls)
]

if getattr(settings, 'DEBUG', False):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jaguarete/tienda/urls.py
from django.urls import path
from . import views

# En este archivo se definirán los linkeos a las views de la aplicación "Tienda".
app_name = "tienda"
urlpatterns = [
    path("", views.home, name="home"),
    path("nosotros/", views.about, name="about"),
    
    # Productos
    path("p/<int:prodId>", views.producto, name="producto"),

    # Para "nuevo" uso la misma view que editar, y decido internamente
    # como armar el form y los botones a presentar.
    path("p/editar/<int:prodId>", views.editarProducto, name="editar"),
    path("p/nuevo", views.editarProducto, name="nuevo"),
    path("p/eliminar", views.eliminarProducto, name="eliminar"),

    # Busqueda/Filtro
    path("busqueda/", views.busqueda, name="busqueda"),
    path("categoria/<str:cat>", views.busqueda, name="categorias"),
    
    # Usuario
    path("perfil/", views.perfil, name="perfil"),
    path("salir/", views.salir, name="salir"),
    
    # Carro
    path("agregar?P<int:prodId>&ref=<path:next>", views.agregarAlCarro, name="agregarAlCarro"),
    path("sacar?P<int:prodId>", views.sacarDelCarro, name="sacar"),
    path("vaciar", views.vaciarCarro, name="vaciar"),
    path("carro/", views.verCarro, name="carro"),
]

jaguarete/usuarios/urls.py
from django.urls import path
from . import views

# En este archivo se definirán los linkeos a las views de la aplicación "Usuarios".
app_name = "usuarios"
urlpatterns = [
    path("login/", views.ingreso, name="ingreso"),
    path("salir/", views.salida, name="salida"),
    path("registro/", views.registro, name="registro"),
]

jaguarete/usuarios/models.py
from django.db import models

# Create your models here.

jaguarete/usuarios/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


# Armo una nueva form de registro con más 
# campos para el registro.
class FormRegistro(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1',
                  'password2', 'first_name', 'last_name']
 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Cambio las etiquetas.
        self.fields['username'].label = "Usuario"
        self.fields['email'].label = "Email"
        self.fields['first_name'].label = "Nombre"
        self.fields['last_name'].label = "Apellido"
        self.fields['password1'].label = "Contraseña"
        self.fields['password2'].label = "Confirmar Contraseña"

        # Fuerzo todo a requerido para el registro.
        self.fields['username'].required = True
        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['password1'].required = True
        self.fields['password2'].required = True

        # Agrego placeholders y una clase por si hay que estilizar.
        self.fields['username'].widget.attrs["class"] = "jag-text-form"
        self.fields['username'].widget.attrs["placeholder"] = self.fields['username'].label
        self.fields['email'].widget.attrs["class"] = "jag-text-form"
        self.fields['email'].widget.attrs["placeholder"] = self.fields['email'].label
        self.fields['first_name'].widget.attrs["class"] = "jag-text-form"
        self.fields['first_name'].widget.attrs["placeholder"] = self.fields['first_name'].label
        self.fields['last_name'].widget.attrs["class"] = "jag-text-form"
        self.fields['last_name'].widget.attrs["placeholder"] = self.fields['last_name'].label
        self.fields['password1'].widget.attrs["class"] = "jag-text-form"
        self.fields['password1'].widget.attrs["placeholder"] = self.fields['password1'].label
        self.fields['password2'].widget.attrs["class"] = "jag-text-form"
        self.fields['password2'].widget.attrs["placeholder"] = self.fields['password2'].label


# Armo una nueva form de login para acomodar los estilos y
# nombres de placeholder
class FormIngreso(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Cambio las etiquetas.
        self.fields['username'].label = "Usuario"
        self.fields['password'].label = "Contraseña"

        # Agrego placeholders y una clase por si hay que estilizar.
        self.fields['username'].widget.attrs["class"] = "jag-text-form"
        self.fields['username'].widget.attrs["placeholder"] = self.fields['username'].label

        self.fields['password'].widget.attrs["class"] = "jag-text-form"
        self.fields['password'].widget.attrs["placeholder"] = self.fields['password'].label

jaguarete/usuarios/views.py
from django.contrib import auth
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render, reverse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .forms import FormRegistro, FormIngreso
from .decorators import not_logged_required


# View de Registro de Usuario.
# Genero el form y lo presento al usuario y 
# recibo por Metodo POST lo que hayan completado.
# Si se valida, lo guardo y lo mando a logearse.
@not_logged_required
def registro(request):
    
    # Si el request es POST, llega con los datos.
    if request.method == 'POST':
        
        # Genero un form con los datos que llegaron.
        form = FormRegistro(request.POST)

        if form.is_valid():
            # Registro el usuario y redirijo a login.
            form.save()
            
            # Genero un mensaje para notificar en la proxima pantalla.
            uname = form.cleaned_data.get('username')
            messages.info(request, f"Usuario {uname.lower()} registrado!")

            # Redirijo a la pantalla de Ingreso.
            return redirect('usuarios:ingreso')
        
        else:
            # Hay errores en los datos.
            for error in form.errors.values():
                messages.info(request, error)    
    else:
        # Si no vengo de un post, vengo de un GET, lo unico que 
        # cambia es que tengo que armar un form vacío.
        form = FormRegistro()

    # El retorno es el mismo en cualquier caso.
    return render(request, "usuarios/registro.html", {'form': form})


# View de Ingreso de Usuario.
# Genero el form y lo presento al usuario y
# recibo por Metodo POST lo que hayan completado.
# Si se valida, lo autentifico y lo mando al HOME de la tienda.
@not_logged_required
def ingreso(request):
    # Si el request es POST, llega con los datos.
    if request.method == 'POST':

        # Autentifico al usuario.
        form = FormIngreso(request.POST)
        nxt = request.POST.get('next')

        uname = request.POST.get('username')
        pword = request.POST.get('password')

        user = authenticate(request, username=uname, password=pword)
        
        if not user:
            messages.info(request, "El usuario o la contraseña son incorrectos.")

        else:
            # Ingreso correcto.
            login(request, user)

            # Redirijo al home de la tienda.
            return HttpResponseRedirect(nxt)

    else:
        # Si no vengo de un post, vengo de un GET, lo unico que
        # cambia es que tengo que armar un form vacío.
        form = FormIngreso()

        # Si vengo redirigido de algun lado, guardo el enlace, 
        # de lo contrario, configuro el home de la tienda.
        nxt = request.GET.get('next')
        if not nxt:
            nxt = reverse('tienda:home')
        
    # El retorno es el mismo en cualquier caso.
    return render(request, "usuarios/login.html", {'form': form, 'next' : nxt})

def salida(request):

    # Desautentifico al usuario del request.    
    logout(request)

    # Redirijo al home
    return redirect('tienda:home')

jaguarete/usuarios/templates/usuarios/layout_user.html
{% load static %}
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {# Linkeo bootstrap. #}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

        {# Linkeo a mi hoja de estilo. #}
        <link rel="stylesheet" href="{% static 'styles/jagkaausers.css' %}">

        {# Linkeo a fuente de Google Fonts para Encabezados principales. #}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nova+Square">

        {# Favicon, ya que arme un icono pequeño lo agrego acá #}
        <link rel="icon" type="image/svg+xml" href="{% static 'images/jag-kaa-logo-sm.svg' %}">


        {# Por si alguna página requiere expandir el header. #}
        {% block private-head %}
        {% endblock %}
        <title>Usuarios de Jaguareté KAA</title>
    </head>
    <body class="d-flex flex-row align-items-center justify-content-center">
        <main class="container col-sm-8 col-md-6 col-lg-4 col-xl-3 text-center">
            {% block private-body %}
            
            {% endblock %}

            <a class="link-atras d-block mb-2" href="{% url 'tienda:home' %}">Volver al sitio</a>

        </main>
    </body>
</html>

jaguarete/usuarios/templates/usuarios/login.html
{% extends 'usuarios/layout_user.html' %}
{% load static %}

{% block private-body %}

<img id="loginImg" src="{% static 'images/jag-kaa-logo.svg' %}" alt="">
<h5 class="text-light mb-4">Ingresá</h5>

<form action="{% url 'usuarios:ingreso' %}" method="POST" class="container form-usuarios">
    {% csrf_token %}

    {{ form.username}}

    {{ form.password }}

    {# Si hay errores de logueo, los paso con mensajes. #}
    {% for mensaje in messages %}
        <div class="alert alert-warning mt-3 mb-0">
            {{ mensaje }}
        </div>
    {% endfor %}

    <br>
    <input type="submit" class="btn d-block mt-3 mx-auto" value="Ingresá">
    <input type="hidden" name="next" value="{{ next }}">

    <br>
    <span class="me-3">¿No tenés una cuenta?</span>
    <a href="{% url 'usuarios:registro' %}" class="card-link">Registrate</a>

</form>

{% endblock %}

jaguarete/usuarios/templates/usuarios/registro.html
{% extends 'usuarios/layout_user.html' %}
{% load static %}

{% block private-body %}

<img id="loginImg" src="{% static 'images/jag-kaa-logo.svg' %}" alt="">
<h5 class="text-light mb-4">Registrate</h5>

<form action="{% url 'usuarios:registro' %}" method="POST" class="container form-usuarios">
    {% csrf_token %}

    {{ form.username}}
    
    {{ form.email }}

    {{ form.first_name }}

    {{ form.last_name }}

    {{ form.password1 }}

    {{ form.password2 }}
    
    {# Si hay errores de registro, los paso con mensajes. #}
    {% for mensaje in messages %}
    <div class="alert alert-warning mt-3 mb-0">
        {{ mensaje }}
    </div>
    {% endfor %}

    <br>
    <input type="submit" class="btn d-block mt-3 mx-auto" value="Nuevo Usuario">
    <br>

    <span class="me-3">¿Ya tenés una cuenta?</span>
    <a href="{% url 'usuarios:ingreso' %}" class="card-link">Ingresá</a>

</form>

{% endblock %}